# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b48c346ad884ade1272d4a110277d8bf2fd7b3b703d65a31dfae906d4e19f2ad3c9393e599895f0d1663f3d1cef00381f92785cba1a607c77bc2b6c71ccb2b52

test:
  secret_key_base: 4e919090d64253232b9af51a0d96f18bcc6c5aabb2592c4f63544e61190a5ebc2a30c11530a9798821329f14f8f22cccd513bc8c8fb4d2be84174baea2f28693

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
